name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Restore projects
    - name: Restore Example project
      run: dotnet restore "src/Example/Example.csproj"

    # Build projects
    - name: Build Example project
      run: dotnet build "src/Example/Example.csproj" --configuration Release --no-restore

    # Test projects
    - name: Test
      run: dotnet test "tests/Example.Tests/Example.Tests.csproj" --no-restore --verbosity normal