name: Dev Release

on:
  push:
    branches: [ master ]
env:
  AZURE_WEBAPP_PACKAGE_NAME: "publish"
  NETCORE_VERSION: "5.0.100"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    # Restore projects
    - name: Restore projects
      run: dotnet restore

    # Build projects
    - name: Build projects
      run: dotnet build --configuration Release --no-restore

    # Test projects
    - name: Test projects
      run: dotnet test SIO-Notifier.sln --configuration Release --no-restore --no-build --verbosity normal --filter Category=Unit -- xunit.parallelizeAssembly=true

    # Publish project
    - name: Publish project
      run: dotnet publish src/SIO.Notifier/SIO.Notifier.csproj --configuration Release -r linux-x64 --self-contained --output ${{ env.AZURE_WEBAPP_PACKAGE_NAME }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_DEV_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_DEV_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_NAME }}